export enum AppSocketEvents {
    REMOTE_COMMAND = "remote-command",
    // SET_PLAYING = "set-playing",
    // CURRENT_VIDEO = "current-video",
    // REMOTE_INIT = "remote-init",
    // SUBTITLE = "subtitle",
    // DISCONNECT = "disconnect",
    // CONNECTION = "connection",
    // REQUEST_SETTINGS = 'request-settings',
    // SEND_SETTINGS = 'send-settings',
    // GET_VIDEOS_DATA = 'get-videos-data',
    // GET_FOLDER_DETAILS = 'get-folder-details',
    // SET_CURRENTTIME = 'set-currenttime',
    // GET_SETTINGS = 'get-settings',
  }